const foodmenu = [
  {
    key: 1,
    name: "Regular Pizza",
    price: "$2.3",
    description: "Made with Italian-style chicken and vegetables",
    button: "Order Now",
    img: "/src/assets/1456_964aeb3c3f235a77992592fcbb955076.png",
  },
  {
    key: 2,
    name: "Nice Burger",
    price: "$2.3",
    description: "Made with Italian-style chicken and vegetables",
    button: "Order Now",
    img: "/src/assets/urdaburger-FT-RECIPE0621-f8488fae404d4ae686d612a7bb201fe3.jpg",
  },
  {
    key: 3,
    name: "Regular Pizza",
    price: "$2.3",
    description: "Made with Italian-style chicken and vegetables",
    button: "Order Now",
    img: "/src/assets/Pizza_food.jpg",
  },
  {
    key: 4,
    name: "Smokey Burger",
    price: "$2.3",
    description: "Made with Italian-style chicken and vegetables",
    button: "Order Now",
    img: "/src/assets/images.jpg",
  },
  {
    key: 5,
    name: "Regular Pizza",
    price: "$2.3",
    description: "Made with Italian-style chicken and vegetables",
    button: "Order Now",
    img: "/src/assets/1456_964aeb3c3f235a77992592fcbb955076.png",
  },
  {
    key: 6,
    name: "Chicken momos",
    price: "$2.3",
    description: "Made with Italian-style chicken and vegetables",
    button: "Order Now",
    img: "/src/assets/chkn_momos2-e1564320413679-500x500.jpg",
  },
];
export default foodmenu;
